using System;
using System.Collections.Generic;

namespace OmniWMS.Infrastructure.Models
{
    public partial class TempIssue
    {
        public string PlanGoodsIssueIndex { get; set; }
        public string OwnerIndex { get; set; }
        public string OwnerId { get; set; }
        public string OwnerName { get; set; }
        public string SoldToIndex { get; set; }
        public string SoldToId { get; set; }
        public string SoldToName { get; set; }
        public string SoldToAddress { get; set; }
        public string ShipToIndex { get; set; }
        public double? ShipToId { get; set; }
        public string ShipToName { get; set; }
        public string ShipToAddress { get; set; }
        public string DocumentTypeIndex { get; set; }
        public string DocumentTypeId { get; set; }
        public string DocumentTypeName { get; set; }
        public string PlanGoodsIssueNo { get; set; }
        public DateTime? PlanGoodsIssueDate { get; set; }
        public DateTime? PlanGoodsIssueDueDate { get; set; }
        public string DocumentRefNo1 { get; set; }
        public string DocumentRefNo2 { get; set; }
        public string DocumentRefNo3 { get; set; }
        public string DocumentRefNo4 { get; set; }
        public string DocumentRefNo5 { get; set; }
        public string DocumentRemark { get; set; }
        public double? DocumentStatus { get; set; }
        public string Udf1 { get; set; }
        public string Udf2 { get; set; }
        public string Udf3 { get; set; }
        public string Udf4 { get; set; }
        public string Udf5 { get; set; }
        public string DocumentPriorityStatus { get; set; }
        public string WarehouseIndex { get; set; }
        public string WarehouseId { get; set; }
        public string WarehouseName { get; set; }
        public string WarehouseIndexTo { get; set; }
        public string WarehouseIdTo { get; set; }
        public string WarehouseNameTo { get; set; }
        public string SoldToSubDistrictIndex { get; set; }
        public string SoldToDistrictIndex { get; set; }
        public string SoldToProvinceIndex { get; set; }
        public string SoldToCountryIndex { get; set; }
        public string SoldToPostcodeIndex { get; set; }
        public string SubDistrictIndex { get; set; }
        public string DistrictIndex { get; set; }
        public string ProvinceIndex { get; set; }
        public string CountryIndex { get; set; }
        public string PostcodeIndex { get; set; }
        public string CreateBy { get; set; }
        public DateTime? CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public string UpdateDate { get; set; }
        public string CancelBy { get; set; }
        public string CancelDate { get; set; }
        public string BackOrderStatus { get; set; }
        public string RoundIndex { get; set; }
        public double? RoundId { get; set; }
        public string RoundName { get; set; }
        public string RouteIndex { get; set; }
        public double? RouteId { get; set; }
        public string RouteName { get; set; }
        public double? PrintTaxInvoice { get; set; }
        public string PaymentType { get; set; }
        public string PaymentCode { get; set; }
        public double? CalGrandTotal { get; set; }
        public string ReasonCodeIndex { get; set; }
        public string ReasonCodeId { get; set; }
        public string ReasonCodeName { get; set; }
        public string RefPlanGoodsIssueIndex { get; set; }
        public string RefPlanGoodsIssueNo { get; set; }
        public string StatusRms { get; set; }
        public string StatusDescRms { get; set; }
        public string VendorId { get; set; }
        public string StplanGoodsIssueDueDate { get; set; }
        public string CreateDateFile { get; set; }
        public string StatusEdi { get; set; }
        public string StatusReason { get; set; }
        public string RoundTime { get; set; }
        public string WarehousePhone { get; set; }
        public string SoldToT1c { get; set; }
        public string SoldToT1cphone { get; set; }
        public string SoldToEmail { get; set; }
        public string SoldToPhone { get; set; }
        public string ShipToCompanyName { get; set; }
        public string ShipToRemark { get; set; }
        public double? ShipToTelephone { get; set; }
        public string ShipToTaxNo { get; set; }
        public string InvoiceName { get; set; }
        public string InvoiceCompanyName { get; set; }
        public string InvoiceAddress { get; set; }
        public string InvoiceRemark { get; set; }
        public double? InvoiceTelephone { get; set; }
        public string InvoiceTaxNo { get; set; }
        public string PaymentIssuer { get; set; }
        public double? CalPromotionDiscount { get; set; }
        public double? CalCpn2Discount { get; set; }
        public double? CalCpn9Discount { get; set; }
        public double? CalEvoucherDiscount { get; set; }
        public double? CalTotalAfterDiscount { get; set; }
        public string DocumentRemarkSub { get; set; }
        public string UserAssign { get; set; }
        public string SoldToNameCus { get; set; }
        public string SoldToTel { get; set; }
        public string SoldToEmailCus { get; set; }
        public string SoldToPhoneCus { get; set; }
        public string SoldToAddressCus { get; set; }
        public string F106 { get; set; }
    }
}
